swagger: "2.0"
info:
  title: Course API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:3000
basePath: /v1
schemes:
  - https
consummes: -application/json
produces: -application/json
paths:
